spring.application.name=dk-salon-backend

spring.datasource.url=${DB_URL:jdbc:postgresql://dpg-d9kvhv3m8hqs738utmn0-a.oregon-postgres.render.com:5432/dl_salon_db}
spring.datasource.username=${DB_USERNAME:dk_user}
spring.datasource.password=${DB_PASSWORD:eAY1WGYRD5GKMC5yM2o68Is9sV4jysH5}

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

server.port=${PORT:8080}
